parameters:
  charset: 'UTF-8'


services:
  context:
    class: Symfony\Component\Routing\RequestContext
  matcher:
    class: Symfony\Component\Routing\Matcher\UrlMatcher
    arguments: [%routes%, '@context']
  requeststack:
    class: Symfony\Component\HttpFoundation\RequestStack
  listener.router:
    class: Symfony\Component\HttpKernel\EventListener\RouterListener
    arguments: ['@matcher', '@requeststack']
  resolver:
    class: Symfony\Component\HttpKernel\Controller\ControllerResolver
  dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    calls:
      - [addSubscriber, ['@listener.router']]
  framework:
    class: Symfony\Component\HttpKernel\HttpKernel
    arguments: ['@dispatcher', '@resolver']